# Generated by Django 5.2.4 on 2025-07-31 08:38

import django.db.models.deletion
import pms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_plan_alter_customuser_profile_picture_emailresetcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.CreateModel(
            name='OwnerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_manager', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_manager', to=settings.AUTH_USER_MODEL)),
                ('property_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_zone_manager', to='pms.propertyzone')),
            ],
        ),
    ]
