# Generated by Django 5.2.4 on 2025-08-02 07:37

import django.utils.timezone
import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_alter_customuser_profile_picture_ownermanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
    ]
