# Generated by Django 5.2.4 on 2025-09-03 07:54

import django.db.models.deletion
import pms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_propertyzone_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.CreateModel(
            name='OwnerStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_staff', to=settings.AUTH_USER_MODEL)),
                ('property_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_zone_staff', to='pms.propertyzone')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
