# Generated by Django 5.2.4 on 2025-09-13 08:58

import django.db.models.deletion
import pms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_alter_customuser_profile_picture_ownerstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysale',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_sale_broker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.AlterField(
            model_name='propertysale',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('sold', 'sold'), ('cancelled', 'cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.02, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saas_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('broker_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('property_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.propertysale')),
            ],
        ),
    ]
