# Generated by Django 5.2.4 on 2025-09-13 09:22

import django.db.models.deletion
import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_propertysale_broker_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertySale',
            new_name='PropertyZoneSale',
        ),
        migrations.RenameField(
            model_name='salespayment',
            old_name='property_sale_id',
            new_name='property_zone_sale_id',
        ),
        migrations.RemoveField(
            model_name='propertyzonesale',
            name='property_id',
        ),
        migrations.AddField(
            model_name='propertyzonesale',
            name='property_zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.propertyzone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.CreateModel(
            name='PropertyZonePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('property_image', models.FileField(blank=True, null=True, upload_to=pms.models.get_property_zone_upload_path, validators=[pms.models.validate_uploaded_image_extension])),
                ('property_zone_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_pictures', to='pms.propertyzone')),
            ],
            options={
                'db_table': 'property_zone_picture',
            },
        ),
    ]
