# Generated by Django 5.2.4 on 2025-09-15 20:35

import django.db.models.deletion
import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_coworkingspace_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyzonesale',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='propertyzonesale',
            name='seller',
        ),
        migrations.AddField(
            model_name='coworkingspace',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coworking_spaces', to='pms.propertyzone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyzonesale',
            name='property_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.property'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='property_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.salespayment'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.AlterField(
            model_name='propertyzonesale',
            name='selling_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyzonesale',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('cancelled', 'cancelled')], max_length=100),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='property_zone_sale_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.propertyzonesale'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('cancelled', 'cancelled')], max_length=100),
        ),
    ]
