# Generated by Django 5.2.4 on 2025-09-17 07:52

import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='coworkingspace',
            unique_together={('name', 'zone')},
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('name', 'property_zone_id')},
        ),
    ]
