# Generated by Django 5.2.4 on 2025-09-18 08:49

import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_brokerprofile_created_at_brokerprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
    ]
