# Generated by Django 5.2.4 on 2025-09-23 18:40

import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_brokerprofile_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpayment',
            name='payment_method',
            field=models.CharField(default='cash', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('cancelled', 'cancelled')], default='pending', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
    ]
