# Generated by Django 5.2.6 on 2025-09-29 13:44

import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_brokertransactions_saastransactions_rent_broker_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SAASTransactions',
            new_name='BrokerTransaction',
        ),
        migrations.RenameModel(
            old_name='brokerTransactions',
            new_name='SAASTransaction',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
    ]
