# Generated by Django 5.2.6 on 2025-10-22 11:17

import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='cycle_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
