# Generated by Django 5.2.6 on 2025-11-04 11:08

import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyzone',
            name='latlong',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='propertyzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='broker_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commission',
            name='saas_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=pms.models.get_upload_path, validators=[pms.models.validate_uploaded_image_extension]),
        ),
        migrations.AlterField(
            model_name='rentcommission',
            name='broker_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rentcommission',
            name='saas_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
